name: Update Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC every day
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Install dependencies
        run: |
          pip install pandas requests advertools  # Add any other dependencies here

      - name: Run Sitemap Extraction
        run: python ./news_react/site.py  # Update the script name and path appropriately

      - name: Run YouTube Videos Fetching
        run: python ./news_react/youtube.py  # Update the script name and path appropriately

      - name: Run Concatenation
        run: python ./news_react/concatenation.py  # Update the script name and path appropriately
